### ISSUE TITLE
Build error - Validate deploy

### ISSUE THREAD

**Issue by balasgit** [cloud-native-toolkit/terraform-gitops-cp-mq-uniform-cluster#7]
Ran test twice but it fails on validate deploy steps with different scenarios

Waiting for 3 instance of Queuemanagers to come up in gitops-cp-mq-uniform-cluster
Timed out waiting for 3 instance of Queuemanagers to come up in gitops-cp-mq-uniform-cluster
No resources found in gitops-cp-mq-uniform-cluster namespace.

- https://github.com/cloud-native-toolkit/terraform-gitops-cp-mq-uniform-cluster/runs/6511896099?check_suite_focus=true#step:15:4292

**Comment by gowdhaman-j** [comment]
Fixed the Issue. The new version is released
